apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          ports:
            - containerPort: {{ .Values.backend.containerPort }}
          env:
            - name: DB_HOST
              value: "{{ .Values.backend.env.DB_HOST }}"
            - name: DB_USER
              value: "{{ .Values.backend.env.DB_USER }}"
            - name: DB_PASSWORD
              value: "{{ .Values.backend.env.DB_PASSWORD }}"
            - name: DB_NAME
              value: "{{ .Values.backend.env.DB_NAME }}"
