apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.containerPort }}
      targetPort: {{ .Values.frontend.containerPort }}
  type: {{ .Values.frontend.service.type }}
